import Head from "next/head";
import Banner from "../components/banner";
import Footer from "../components/footer/Footer";
import Header from "../components/header/Header";
import Suggestions from "../components/suggestion";

export default function Layout({ content }: any) {
  return (
    <>
      <Head>
        <title>Cars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel='stylesheet' href='//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&amp;subset=latin-ext' />
        <link rel='stylesheet' href='//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese' />
      </Head>
      <Header />
      <Banner />
      { content }
      <Suggestions />
      <Footer />
    </>
  );
}