import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner'
import List from '../components/car/list'
import Footer from '../components/footer/Footer'
import Header from '../components/header/Header'
import Suggestions from '../components/suggestion'

const Home: NextPage = (data: any) => {
  let suggestion = [
    {
      name: data.cars[0].title,
      url: data.cars[0].imageUrl
    },
    {
      name: data.cars[1].title,
      url: data.cars[1].imageUrl
    }
  ];

  return (
    <div>
      <Head>
        <title>Cars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel='stylesheet' href='//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&amp;subset=latin-ext' />
        <link rel='stylesheet' href='//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese' />
      </Head>
      <Header />
      <Banner img={data.cars[0].imageUrl}/>
      <List data={data} />
      <Suggestions data={suggestion}/>
      <Footer />
    </div>
  )
}

export async function getServerSideProps({ req, res }: any) {
  res.setHeader(
    'Cache-Control',
    'public, s-maxage=120, stale-while-revalidate=120'
  )

  // Fetch brands name
  const makeRes = await fetch(`https://api.staging.myautochek.com/v1/inventory/make?popular=true`);
  const makeData = await makeRes.json();


  // Fetch list of cars
  const carsRes = await fetch(`https://api.staging.myautochek.com/v1/inventory/car/search?country=NG`)
  const carsData = await carsRes.json()

  // Pass data to the page via props
  return { props: { brands: makeData.makeList, cars: carsData.result } }
}

export default Home;
