import { NextPage } from "next";
import Head from "next/head";
import Banner from "../../components/banner";
import Details from "../../components/car/details";
import Footer from "../../components/footer/Footer";
import Header from "../../components/header/Header";
import Suggestions from "../../components/suggestion";

const Car: NextPage = (data: any) => {
  let suggestion = [
    {
      name: data.media.carMediaList[0].name,
      url: data.media.carMediaList[0].url
    },
    {
      name: data.media.carMediaList[1].name,
      url: data.media.carMediaList[1].url
    }
  ];

  return (
    <div>
      <Head>
        <title>{data.details.carName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel='stylesheet' href='//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&amp;subset=latin-ext' />
        <link rel='stylesheet' href='//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese' />

        <script src="/js/jquery.min.js"></script>
        <script src="/js/jquery.flexslider.js"></script>
        <script src="/js/image-zoom.js"></script>
        <script src="/js/custom.js"></script>
      </Head>
      <Header />
      <Banner img={data.details.imageUrl}/>
      <Details data={data} />
      <Suggestions data={suggestion} />
      <Footer />
    </div>
  )
}

export async function getServerSideProps({params,  req, res}: any) {
  res.setHeader(
    'Cache-Control',
    'public, s-maxage=3600, stale-while-revalidate=3600'
  )

  // Fetch data from external API
  const detailsRes = await fetch(`https://api.staging.myautochek.com/v1/inventory/car/${params.id}`);
  const data = await detailsRes.json();

  const mediaRes = await fetch(`https://api.staging.myautochek.com/v1/inventory/car_media?carId=${params.id}`);
  const mediaData = await mediaRes.json();

  // Pass data to the page via props
  return { props: { details: data, media: mediaData } }
}

export default Car;